### ISSUE TITLE
The algorithm can not keep running in background

### ISSUE THREAD

**Issue by Amab** [JJ/splash-volunteer#14]
When the tab loses the focus execution halts. The algorithm can not keep running in background.

Browser: Firefox 37.0.1
OS: Kubuntu 14.10

**Comment by JJ** [comment]
I'm not sure that's a bug. It could be a feature :-)
Maybe we could complicate it with WebWorkers (it's a suggestion by
@mariosky) but not sure it would be worth the while.

**Comment by Amab** [comment]
I'm not sure how long it takes each execution to obtain useful results, but if the algorithm is paused when it loses focus I can not continue browsing on other tabs if I want to contribute. Users can leave open the web a few minutes but will not want to leave it open one hour without being able to browse other websites from other tabs.

**Comment by JJ** [comment]
2015-04-12 9:44 GMT+02:00 Juan Miguel Boyero Corral <
notifications@github.com>:

> I'm not sure how long it takes each execution to obtain useful results,
> but if the algorithm is paused when it loses focus I can not continue
> browsing on other tabs if I want to contribute. Users can leave open the
> web a few minutes but will not want to leave it open one hour without being
> able to browse other websites from other tabs.
>
>  As I said, it's no big deal. If user loses focus, the algorithm loses
focus and performance lowers. If we have to run something in the
background, it's better to ask permission. And if you have to ask
permission *always*, you lose users. You can also be obnoxious and ask
permission only if it loses focus but then most people will say, what the
hell, no way. The whole point of the experiment is to collect as many users
as possible, not as much CPU as possible. Your point is valid, but we would
rather address it by making them stay on the page, with more attractive
content maybe?

**Comment by Amab** [comment]
You're right, but it can be confusing to users. Users may think they are contributing leaving open the web in the background while browsing other sites on other tabs when it is not true. Maybe you could warn users of the need to maintain the web in focus to contribute.

**Comment by JJ** [comment]
I'll add it to the info. Thanks!
