### ISSUE TITLE
Use Bower

### ISSUE THREAD

**Issue by iblancasa** [JJ/splash-volunteer#28]
Here https://github.com/JJ/splash-volunteer/tree/master/public/js you have two Javascript libraries (Char.js and Kube)
How about use bower to donwload it instead have it in the repo?

**Comment by JJ** [comment]
Yep, I should do that...

**Comment by iblancasa** [comment]
You are using Char.JS from a CDN and Kube is deprecated (has no sense to use bower)

**Comment by JJ** [comment]
why is it deprecated?

**Comment by iblancasa** [comment]
Last released was not so good and website developers decided stop use it



Enviado desde mi iPad

**Comment by JJ** [comment]
Any alternative? We are not using it so much, just for layout and icons.

**Comment by iblancasa** [comment]
I think it is good for now.
